baseURL = 'https://exmachina.in/'
publishDir = "docs"
languageCode = 'en'
title = 'Ex Machina'
theme = "mainroad"

pluralizelisttitles = false
dateformat = "2006-01-02" # Change the format of dates

enableRSS = true
showToc = true

[pagination]
pagersize=10

[permalinks]
  posts = '/:day/:month/:year/:title/'

# Add page to a main, side, and footer menu
menu = "main"


[menu]
[[menu.main]]
  name = 'About' # Name of the menu item
  pre = "<i class='fa fa-road'></i>" # Icon of the menu item
  url = '/about/' # URL of the menu item
  weight = 5 # Weight of the menu item
[[menu.main]]
  name = 'Podcast'
  pre = "<i class='fa fa-road'></i>" # Icon of the menu item
  url = '/podcast/' # URL of the menu item
  weight = 4 # Weight of the menu item
[[menu.main]]
  name = 'Books'
  pre = "<i class='fa fa-road'></i>"
  url = '/books/' # URL of the menu item
  weight = 3 # Weight of the menu item
[[menu.main]]
    identifier = "chronological-feed" # Identifier of the menu item
    name = "Index"
    url = "/index/" # URL of the menu item
    weight = 1 # Weight of the menu item
[[menu.main]]
    identifier = "topics" # Identifier of the menu item
    name = "Topics"
    url = "/topics/" # URL of the menu item
    weight = 2 # Weight of the menu item


[Params]
  description = "Rahul Matthan's Collected Writings" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["posts", "about"]


[Params.author]
  name = "Rahul Matthan"
  bio = "Rahul Matthan is a lawyer who works at the intersection of law, technology and society."
  avatar = "/images/avatar.png"

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default) 

[Params.logo]
  image = "/images/exmachina.jpg"
  title = "Ex Machina"
  subtitle = "Law. Technology. Society."

[Params.thumbnail]
  # Show thumbnail only for list items
  visibility = ["list"]

[Params.sidebar]
  home = "right"
  list = "false"
  single = "false"
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "matthan"
  instagram = "matthan"
  linkedin = "rahulmatthan"
  